version: '3.8'
services:
  database:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  api: 
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: yarn start:dev
    env_file:
      - .env
    depends_on:
      - database

volumes:
  mongodb_data_container: